export type PropertyStatus = "AVAILABLE" | "PRICE_PENDING" | "SOLD" | "PURCHASE_IN_PROGRESS";

export type Property = {
  project: string;
  location: string;
  block: string;
  shgb: string;
  floor: string;
  buildingArea: number;
  landArea: number | null;
  price: number | null;
  status: PropertyStatus;
};

export const properties: Property[] = [
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "K.1-11",
    shgb: "5044",
    floor: "2 lantai",
    buildingArea: 93,
    landArea: 105,
    price: 2000000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "K.1-15",
    shgb: "5043",
    floor: "2 lantai",
    buildingArea: 93,
    landArea: 105,
    price: 2000000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "K.1-17",
    shgb: "5042",
    floor: "2 lantai",
    buildingArea: 93,
    landArea: 105,
    price: 2000000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "K.1-19",
    shgb: "5041",
    floor: "2 lantai",
    buildingArea: 93,
    landArea: 105,
    price: 2000000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "K.1-21",
    shgb: "5040",
    floor: "2 lantai",
    buildingArea: 93,
    landArea: 105,
    price: 2000000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "K.1-23",
    shgb: "5039",
    floor: "2 lantai",
    buildingArea: 93,
    landArea: 105,
    price: 2000000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "K.1-25",
    shgb: "5038",
    floor: "2 lantai",
    buildingArea: 93,
    landArea: 105,
    price: 2000000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "K.1-27",
    shgb: "5037",
    floor: "2 lantai",
    buildingArea: 93,
    landArea: 105,
    price: 2000000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "K.1-29",
    shgb: "5036",
    floor: "2 lantai",
    buildingArea: 93,
    landArea: 105,
    price: 2000000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "K.1-31",
    shgb: "5035",
    floor: "2 lantai",
    buildingArea: 93,
    landArea: 105,
    price: 2000000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "K.1-33",
    shgb: "5034",
    floor: "2 lantai",
    buildingArea: 93,
    landArea: 105,
    price: 2000000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "K.1-35",
    shgb: "5033",
    floor: "2 lantai",
    buildingArea: 93,
    landArea: 105,
    price: 2000000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "K.1-37",
    shgb: "5032",
    floor: "2 lantai",
    buildingArea: 93,
    landArea: 105,
    price: 2000000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "K.1-39",
    shgb: "5031",
    floor: "2 lantai",
    buildingArea: 93,
    landArea: 105,
    price: 2000000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "L-02",
    shgb: "5084",
    floor: "2 lantai",
    buildingArea: 93,
    landArea: 105,
    price: 2060000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "L-04",
    shgb: "5085",
    floor: "2 lantai",
    buildingArea: 93,
    landArea: 105,
    price: 2000000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "L-06",
    shgb: "5086",
    floor: "2 lantai",
    buildingArea: 93,
    landArea: 105,
    price: 2000000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "L-08",
    shgb: "5087",
    floor: "2 lantai",
    buildingArea: 80,
    landArea: 90,
    price: 1760000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "L-10",
    shgb: "5088",
    floor: "2 lantai",
    buildingArea: 80,
    landArea: 90,
    price: 1760000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "L-12",
    shgb: "5089",
    floor: "2 lantai",
    buildingArea: 80,
    landArea: 90,
    price: 1760000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "L-14",
    shgb: "5090",
    floor: "2 lantai",
    buildingArea: 80,
    landArea: 90,
    price: 1760000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "L-16",
    shgb: "5091",
    floor: "2 lantai",
    buildingArea: 80,
    landArea: 90,
    price: 1760000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "L-18",
    shgb: "5092",
    floor: "2 lantai",
    buildingArea: 80,
    landArea: 90,
    price: 1760000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "L-20",
    shgb: "5093",
    floor: "2 lantai",
    buildingArea: 80,
    landArea: 90,
    price: 1760000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "L-22",
    shgb: "5094",
    floor: "2 lantai",
    buildingArea: 80,
    landArea: 90,
    price: 1760000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "L-24",
    shgb: "5095",
    floor: "2 lantai",
    buildingArea: 80,
    landArea: 90,
    price: 1760000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "L-26",
    shgb: "5096",
    floor: "2 lantai",
    buildingArea: 80,
    landArea: 90,
    price: 1760000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "L-28",
    shgb: "5097",
    floor: "2 lantai",
    buildingArea: 80,
    landArea: 90,
    price: 1760000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "L-30",
    shgb: "5098",
    floor: "2 lantai",
    buildingArea: 80,
    landArea: 90,
    price: 1760000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "L-32",
    shgb: "5099",
    floor: "2 lantai",
    buildingArea: 80,
    landArea: 90,
    price: 1760000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "L-34",
    shgb: "5100",
    floor: "2 lantai",
    buildingArea: 80,
    landArea: 90,
    price: 1760000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "L-36",
    shgb: "5101",
    floor: "2 lantai",
    buildingArea: 80,
    landArea: 90,
    price: 1760000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "L-38",
    shgb: "5102",
    floor: "2 lantai",
    buildingArea: 80,
    landArea: 90,
    price: 1760000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "L-40",
    shgb: "5103",
    floor: "2 lantai",
    buildingArea: 80,
    landArea: 90,
    price: 1760000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "L-42",
    shgb: "5104",
    floor: "2 lantai",
    buildingArea: 80,
    landArea: 90,
    price: 1760000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "L.1-01",
    shgb: "5130",
    floor: "2 lantai",
    buildingArea: 93,
    landArea: 105,
    price: 2060000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "L.1-03",
    shgb: "5129",
    floor: "2 lantai",
    buildingArea: 93,
    landArea: 105,
    price: 2000000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "L.1-05",
    shgb: "5128",
    floor: "2 lantai",
    buildingArea: 93,
    landArea: 105,
    price: 2000000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "L.1-07",
    shgb: "5127",
    floor: "2 lantai",
    buildingArea: 93,
    landArea: 105,
    price: 2000000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "L.1-09",
    shgb: "5126",
    floor: "2 lantai",
    buildingArea: 80,
    landArea: 90,
    price: 1760000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "L.1-11",
    shgb: "5125",
    floor: "2 lantai",
    buildingArea: 80,
    landArea: 90,
    price: 1760000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "L.1-15",
    shgb: "5124",
    floor: "2 lantai",
    buildingArea: 80,
    landArea: 90,
    price: 1760000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "L.1-17",
    shgb: "5123",
    floor: "2 lantai",
    buildingArea: 80,
    landArea: 90,
    price: 1760000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "L.1-19",
    shgb: "5122",
    floor: "2 lantai",
    buildingArea: 80,
    landArea: 90,
    price: 1760000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "L.1-21",
    shgb: "5121",
    floor: "2 lantai",
    buildingArea: 80,
    landArea: 90,
    price: 1760000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "L.1-23",
    shgb: "5120",
    floor: "2 lantai",
    buildingArea: 80,
    landArea: 90,
    price: 1760000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "L.1-25",
    shgb: "5119",
    floor: "2 lantai",
    buildingArea: 80,
    landArea: 90,
    price: 1760000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "L.1-27",
    shgb: "5118",
    floor: "2 lantai",
    buildingArea: 80,
    landArea: 90,
    price: 1760000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "L.1-29",
    shgb: "5117",
    floor: "2 lantai",
    buildingArea: 80,
    landArea: 90,
    price: 1760000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "L.1-31",
    shgb: "5116",
    floor: "2 lantai",
    buildingArea: 80,
    landArea: 90,
    price: 1760000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "L.1-33",
    shgb: "5115",
    floor: "2 lantai",
    buildingArea: 80,
    landArea: 90,
    price: 1760000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "L.1-39",
    shgb: "5112",
    floor: "2 lantai",
    buildingArea: 80,
    landArea: 90,
    price: 1760000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "L.1-41",
    shgb: "5111",
    floor: "2 lantai",
    buildingArea: 80,
    landArea: 90,
    price: 1760000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "L.1-43",
    shgb: "5110",
    floor: "2 lantai",
    buildingArea: 80,
    landArea: 90,
    price: 1760000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "L.1-45",
    shgb: "5109",
    floor: "2 lantai",
    buildingArea: 93,
    landArea: 105,
    price: 2000000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "M-02",
    shgb: "5133",
    floor: "2 lantai",
    buildingArea: 93,
    landArea: 105,
    price: 2060000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "M-04",
    shgb: "5134",
    floor: "2 lantai",
    buildingArea: 80,
    landArea: 90,
    price: 1760000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "M-06",
    shgb: "5135",
    floor: "2 lantai",
    buildingArea: 80,
    landArea: 90,
    price: 1760000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "M-08",
    shgb: "5136",
    floor: "2 lantai",
    buildingArea: 80,
    landArea: 90,
    price: 1760000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "M-10",
    shgb: "5137",
    floor: "2 lantai",
    buildingArea: 80,
    landArea: 90,
    price: 1760000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "M-12",
    shgb: "5138",
    floor: "2 lantai",
    buildingArea: 80,
    landArea: 90,
    price: 1760000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "M-14",
    shgb: "5139",
    floor: "2 lantai",
    buildingArea: 80,
    landArea: 90,
    price: 1760000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "M-16",
    shgb: "5140",
    floor: "2 lantai",
    buildingArea: 80,
    landArea: 90,
    price: 1760000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "M-18",
    shgb: "5141",
    floor: "2 lantai",
    buildingArea: 80,
    landArea: 90,
    price: 1760000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "M-20",
    shgb: "5142",
    floor: "2 lantai",
    buildingArea: 80,
    landArea: 90,
    price: 1760000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "M-22",
    shgb: "5143",
    floor: "2 lantai",
    buildingArea: 80,
    landArea: 90,
    price: 1760000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "M-24",
    shgb: "5144",
    floor: "2 lantai",
    buildingArea: 80,
    landArea: 90,
    price: 1760000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "M-26",
    shgb: "5145",
    floor: "2 lantai",
    buildingArea: 80,
    landArea: 90,
    price: 1760000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "M-28",
    shgb: "5146",
    floor: "2 lantai",
    buildingArea: 80,
    landArea: 90,
    price: 1760000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "M-30",
    shgb: "5147",
    floor: "2 lantai",
    buildingArea: 80,
    landArea: 90,
    price: 1760000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "O-12",
    shgb: "4619",
    floor: "1 lantai",
    buildingArea: 66,
    landArea: 100,
    price: 1420000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "O-16",
    shgb: "4617",
    floor: "1 lantai",
    buildingArea: 67,
    landArea: 101,
    price: 1428000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "O-18",
    shgb: "4616",
    floor: "1 lantai",
    buildingArea: 73,
    landArea: 102,
    price: 1475000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "O-20",
    shgb: "4615",
    floor: "1 lantai",
    buildingArea: 73,
    landArea: 102,
    price: 1475000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "O-22",
    shgb: "4614",
    floor: "1 lantai",
    buildingArea: 74,
    landArea: 103,
    price: 1490000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "O-24",
    shgb: "",
    floor: "1 lantai",
    buildingArea: 74,
    landArea: null,
    price: null,
    status: "PRICE_PENDING",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "N-22",
    shgb: "",
    floor: "1 lantai",
    buildingArea: 56,
    landArea: 84,
    price: null,
    status: "PRICE_PENDING",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "N-24",
    shgb: "",
    floor: "1 lantai",
    buildingArea: 56,
    landArea: 84,
    price: null,
    status: "PRICE_PENDING",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "N-28",
    shgb: "4661",
    floor: "1 lantai",
    buildingArea: 56,
    landArea: 84,
    price: 1256000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "N-30",
    shgb: "4662",
    floor: "1 lantai",
    buildingArea: 56,
    landArea: 84,
    price: 1256000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "N-32",
    shgb: "",
    floor: "1 lantai",
    buildingArea: 56,
    landArea: 84,
    price: null,
    status: "PRICE_PENDING",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "N-34",
    shgb: "",
    floor: "1 lantai",
    buildingArea: 56,
    landArea: 84,
    price: null,
    status: "PRICE_PENDING",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "N-36",
    shgb: "",
    floor: "1 lantai",
    buildingArea: 56,
    landArea: 84,
    price: null,
    status: "PRICE_PENDING",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "N-40",
    shgb: "",
    floor: "1 lantai",
    buildingArea: 56,
    landArea: 84,
    price: null,
    status: "PRICE_PENDING",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "N-42",
    shgb: "",
    floor: "1 lantai",
    buildingArea: 56,
    landArea: 84,
    price: null,
    status: "PRICE_PENDING",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "N-44",
    shgb: "",
    floor: "1 lantai",
    buildingArea: 56,
    landArea: 84,
    price: null,
    status: "PRICE_PENDING",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "N-46",
    shgb: "4670",
    floor: "1 lantai",
    buildingArea: 56,
    landArea: 84,
    price: 1256000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "N1-17",
    shgb: "",
    floor: "1 lantai",
    buildingArea: 62,
    landArea: 91,
    price: null,
    status: "PRICE_PENDING",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "N1-25",
    shgb: "",
    floor: "1 lantai",
    buildingArea: 62,
    landArea: 91,
    price: null,
    status: "PRICE_PENDING",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "N1-27",
    shgb: "",
    floor: "1 lantai",
    buildingArea: 62,
    landArea: 91,
    price: null,
    status: "PRICE_PENDING",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "M1-23",
    shgb: "4686/5169",
    floor: "1 lantai",
    buildingArea: 56,
    landArea: 84,
    price: 1256000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "M1-25",
    shgb: "4685/5168",
    floor: "1 lantai",
    buildingArea: 56,
    landArea: 84,
    price: 1256000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "M1-27",
    shgb: "4684/5167",
    floor: "1 lantai",
    buildingArea: 56,
    landArea: 84,
    price: 1256000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "M1-29",
    shgb: "4683/5166",
    floor: "1 lantai",
    buildingArea: 56,
    landArea: 84,
    price: 1256000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "M1-31",
    shgb: "4682/5165",
    floor: "1 lantai",
    buildingArea: 56,
    landArea: 84,
    price: 1256000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Semanggi",
    location: "Surabaya Timur",
    block: "M1-33",
    shgb: "4681/5164",
    floor: "1 lantai",
    buildingArea: 56,
    landArea: 84,
    price: 1256000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "PU-96",
    shgb: "848",
    floor: "2 lantai",
    buildingArea: 120,
    landArea: 230,
    price: 2502500000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "PU-98",
    shgb: "846",
    floor: "2 lantai",
    buildingArea: 120,
    landArea: 230,
    price: 2502500000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "A4-02",
    shgb: "9147.0",
    floor: "2 lantai",
    buildingArea: 157,
    landArea: 100,
    price: 2073000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "A4-04",
    shgb: "9148.0",
    floor: "2 lantai",
    buildingArea: 120,
    landArea: 100,
    price: 1740000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "A4-06",
    shgb: "904",
    floor: "2 lantai",
    buildingArea: 120,
    landArea: 100,
    price: 1740000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "A4-08",
    shgb: "905",
    floor: "2 lantai",
    buildingArea: 120,
    landArea: 100,
    price: 1740000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "A4-10",
    shgb: "971",
    floor: "2 lantai",
    buildingArea: 120,
    landArea: 100,
    price: 1740000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "A4-12",
    shgb: "970",
    floor: "2 lantai",
    buildingArea: 120,
    landArea: 100,
    price: 1740000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "A4-14",
    shgb: "969",
    floor: "2 lantai",
    buildingArea: 120,
    landArea: 100,
    price: 1740000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "A4-16",
    shgb: "968",
    floor: "2 lantai",
    buildingArea: 170,
    landArea: 100,
    price: 2190000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "B4-02",
    shgb: "9151.0",
    floor: "2 lantai",
    buildingArea: 120,
    landArea: 82,
    price: 1621200000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "B4-04",
    shgb: "9152.0",
    floor: "2 lantai",
    buildingArea: 84,
    landArea: 82,
    price: 1297200000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "B4-06",
    shgb: "9155.0",
    floor: "2 lantai",
    buildingArea: 84,
    landArea: 82,
    price: 1297200000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "B4-08",
    shgb: "9156.0",
    floor: "2 lantai",
    buildingArea: 84,
    landArea: 82,
    price: 1297200000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "B4-10",
    shgb: "9158.0",
    floor: "2 lantai",
    buildingArea: 84,
    landArea: 82,
    price: 1297200000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "C4-01",
    shgb: "9150.0",
    floor: "2 lantai",
    buildingArea: 120,
    landArea: 82,
    price: 1621200000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "C4-03",
    shgb: "9153.0",
    floor: "2 lantai",
    buildingArea: 84,
    landArea: 82,
    price: 1297200000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "C4-05",
    shgb: "9154.0",
    floor: "2 lantai",
    buildingArea: 84,
    landArea: 82,
    price: 1297200000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "C4-07",
    shgb: "892",
    floor: "2 lantai",
    buildingArea: 116,
    landArea: 82,
    price: 1585200000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "C4-02",
    shgb: "867",
    floor: "2 lantai",
    buildingArea: 82,
    landArea: 142,
    price: 1819200000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "C4-04",
    shgb: "866",
    floor: "2 lantai",
    buildingArea: 82,
    landArea: 98,
    price: 1423200000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "C4-06",
    shgb: "897",
    floor: "2 lantai",
    buildingArea: 82,
    landArea: 99,
    price: 1423200000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "C4-08",
    shgb: "893",
    floor: "2 lantai",
    buildingArea: 82,
    landArea: 100,
    price: 1423200000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "C4-10",
    shgb: "864",
    floor: "2 lantai",
    buildingArea: 82,
    landArea: 130,
    price: 1711200000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "D4-01",
    shgb: "974",
    floor: "2 lantai",
    buildingArea: 82,
    landArea: 153,
    price: 1918200000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "D4-02",
    shgb: "898",
    floor: "2 lantai",
    buildingArea: 82,
    landArea: 196,
    price: 2305200000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "D4-03",
    shgb: "895",
    floor: "2 lantai",
    buildingArea: 82,
    landArea: 105,
    price: 1486200000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "D4-04",
    shgb: "899",
    floor: "2 lantai",
    buildingArea: 82,
    landArea: 118,
    price: 1603200000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "D4-05",
    shgb: "896",
    floor: "2 lantai",
    buildingArea: 82,
    landArea: 105,
    price: 1486200000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "D4-06",
    shgb: "900",
    floor: "2 lantai",
    buildingArea: 82,
    landArea: 114,
    price: 1567200000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "D4-07",
    shgb: "894",
    floor: "2 lantai",
    buildingArea: 82,
    landArea: 105,
    price: 1486200000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "D4-08",
    shgb: "901",
    floor: "2 lantai",
    buildingArea: 82,
    landArea: 110,
    price: 1531200000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "D4-10",
    shgb: "902",
    floor: "2 lantai",
    buildingArea: 82,
    landArea: 107,
    price: 1504200000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "D4-12",
    shgb: "972",
    floor: "2 lantai",
    buildingArea: 82,
    landArea: 103,
    price: 1468200000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "D4-14",
    shgb: "903",
    floor: "2 lantai",
    buildingArea: 82,
    landArea: 154,
    price: 1927200000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "PU-02",
    shgb: "456",
    floor: "2 lantai",
    buildingArea: 135,
    landArea: 79,
    price: 1800000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "PU-04",
    shgb: "457",
    floor: "2 lantai",
    buildingArea: 135,
    landArea: 73,
    price: 1800000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "PU-06",
    shgb: "661",
    floor: "2 lantai",
    buildingArea: 135,
    landArea: 80,
    price: 1800000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "PU-08",
    shgb: "660",
    floor: "2 lantai",
    buildingArea: 135,
    landArea: 88,
    price: 1800000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "PU-10",
    shgb: "659",
    floor: "2 lantai",
    buildingArea: 135,
    landArea: 95,
    price: 1800000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "PU-12",
    shgb: "658",
    floor: "2 lantai",
    buildingArea: 135,
    landArea: 103,
    price: 1800000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "PU-14",
    shgb: "662",
    floor: "2 lantai",
    buildingArea: 135,
    landArea: 110,
    price: 1800000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "PU-16",
    shgb: "663",
    floor: "2 lantai",
    buildingArea: 135,
    landArea: 118,
    price: 1800000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "PU-18",
    shgb: "647",
    floor: "2 lantai",
    buildingArea: 135,
    landArea: 81,
    price: 1800000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "PU-20",
    shgb: "664",
    floor: "2 lantai",
    buildingArea: 135,
    landArea: 81,
    price: 1800000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "PU-22",
    shgb: "650",
    floor: "2 lantai",
    buildingArea: 135,
    landArea: 81,
    price: 1800000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "PU-24",
    shgb: "651",
    floor: "2 lantai",
    buildingArea: 135,
    landArea: 81,
    price: 1800000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "PU-26",
    shgb: "667",
    floor: "2 lantai",
    buildingArea: 135,
    landArea: 81,
    price: 1800000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "PU-28",
    shgb: "653",
    floor: "2 lantai",
    buildingArea: 135,
    landArea: 81,
    price: 1800000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "PU-30",
    shgb: "666",
    floor: "2 lantai",
    buildingArea: 135,
    landArea: 81,
    price: 1800000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "PU-32",
    shgb: "665",
    floor: "2 lantai",
    buildingArea: 135,
    landArea: 81,
    price: 1800000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "PU-34",
    shgb: "656",
    floor: "2 lantai",
    buildingArea: 135,
    landArea: 81,
    price: 1800000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "PU-36",
    shgb: "671",
    floor: "2 lantai",
    buildingArea: 135,
    landArea: 81,
    price: 1800000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "PU-38",
    shgb: "670",
    floor: "2 lantai",
    buildingArea: 135,
    landArea: 81,
    price: 1800000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "PU-40",
    shgb: "639",
    floor: "2 lantai",
    buildingArea: 135,
    landArea: 81,
    price: 1800000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "PU-42",
    shgb: "669",
    floor: "2 lantai",
    buildingArea: 135,
    landArea: 81,
    price: 1800000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "PU-44",
    shgb: "668",
    floor: "2 lantai",
    buildingArea: 135,
    landArea: 81,
    price: 1800000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "PU-46",
    shgb: "642",
    floor: "2 lantai",
    buildingArea: 135,
    landArea: 81,
    price: 1800000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "PU-48",
    shgb: "674",
    floor: "2 lantai",
    buildingArea: 135,
    landArea: 81,
    price: 1800000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "PU-50",
    shgb: "645",
    floor: "2 lantai",
    buildingArea: 135,
    landArea: 81,
    price: 1800000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "PU-52",
    shgb: "673",
    floor: "2 lantai",
    buildingArea: 135,
    landArea: 81,
    price: 1800000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "PU-54",
    shgb: "672",
    floor: "2 lantai",
    buildingArea: 135,
    landArea: 81,
    price: 1800000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "PU-56",
    shgb: "631",
    floor: "2 lantai",
    buildingArea: 135,
    landArea: 81,
    price: 1800000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "PU-58",
    shgb: "633",
    floor: "2 lantai",
    buildingArea: 135,
    landArea: 81,
    price: 1800000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "PU-60",
    shgb: "678",
    floor: "2 lantai",
    buildingArea: 135,
    landArea: 81,
    price: 1800000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "PU-62",
    shgb: "677",
    floor: "2 lantai",
    buildingArea: 135,
    landArea: 81,
    price: 1800000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "PU-64",
    shgb: "676",
    floor: "2 lantai",
    buildingArea: 135,
    landArea: 81,
    price: 1800000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "PU-66",
    shgb: "675",
    floor: "2 lantai",
    buildingArea: 135,
    landArea: 81,
    price: 1800000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "PU-68",
    shgb: "637",
    floor: "2 lantai",
    buildingArea: 135,
    landArea: 81,
    price: 1800000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "PU-70",
    shgb: "625",
    floor: "2 lantai",
    buildingArea: 135,
    landArea: 81,
    price: 1800000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "PU-72",
    shgb: "681",
    floor: "2 lantai",
    buildingArea: 135,
    landArea: 81,
    price: 1800000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "PU-74",
    shgb: "680",
    floor: "2 lantai",
    buildingArea: 135,
    landArea: 81,
    price: 1800000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "PU-76",
    shgb: "679",
    floor: "2 lantai",
    buildingArea: 135,
    landArea: 81,
    price: 1800000000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "C7-08",
    shgb: "925",
    floor: "1 lantai",
    buildingArea: 52,
    landArea: 98,
    price: 1040300000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "D7-12",
    shgb: "944",
    floor: "1 lantai",
    buildingArea: 52,
    landArea: 105,
    price: 1066950000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "D7-14",
    shgb: "943",
    floor: "1 lantai",
    buildingArea: 52,
    landArea: 105,
    price: 1066950000,
    status: "AVAILABLE",
  },
  {
    project: "Wisata Bukit Sentul",
    location: "Malang",
    block: "D7-16",
    shgb: "942",
    floor: "1 lantai",
    buildingArea: 52,
    landArea: 105,
    price: 1066950000,
    status: "AVAILABLE",
  },
  {
    project: "Blukid Residence 3",
    location: "Sidoarjo",
    block: "A-03",
    shgb: "2726",
    floor: "2 lantai",
    buildingArea: 91,
    landArea: 120,
    price: 1428000000,
    status: "AVAILABLE",
  },
  {
    project: "Blukid Residence 3",
    location: "Sidoarjo",
    block: "A-14",
    shgb: "2736",
    floor: "2 lantai",
    buildingArea: 91,
    landArea: 115,
    price: 1400000000,
    status: "AVAILABLE",
  },
  {
    project: "Blukid Residence 3",
    location: "Sidoarjo",
    block: "A-22",
    shgb: "2744",
    floor: "1 lantai",
    buildingArea: 42,
    landArea: 90,
    price: 817000000,
    status: "AVAILABLE",
  },
  {
    project: "Blukid Residence 3",
    location: "Sidoarjo",
    block: "A-23",
    shgb: "2745",
    floor: "1 lantai",
    buildingArea: 42,
    landArea: 90,
    price: 817000000,
    status: "AVAILABLE",
  },
  {
    project: "Blukid Residence 3",
    location: "Sidoarjo",
    block: "A-26",
    shgb: "2748",
    floor: "1 lantai",
    buildingArea: 42,
    landArea: 90,
    price: 817000000,
    status: "AVAILABLE",
  },
  {
    project: "Blukid Residence 3",
    location: "Sidoarjo",
    block: "A-27",
    shgb: "2749",
    floor: "1 lantai",
    buildingArea: 42,
    landArea: 90,
    price: 817000000,
    status: "AVAILABLE",
  },
  {
    project: "Blukid Residence 3",
    location: "Sidoarjo",
    block: "A-32",
    shgb: "2754",
    floor: "1 lantai",
    buildingArea: 42,
    landArea: 90,
    price: 817000000,
    status: "AVAILABLE",
  },
  {
    project: "Blukid Residence 3",
    location: "Sidoarjo",
    block: "A-33",
    shgb: "2755",
    floor: "1 lantai",
    buildingArea: 42,
    landArea: 90,
    price: 817000000,
    status: "AVAILABLE",
  },
  {
    project: "Blukid Residence 3",
    location: "Sidoarjo",
    block: "A-34",
    shgb: "2756",
    floor: "1 lantai",
    buildingArea: 42,
    landArea: 90,
    price: 817000000,
    status: "AVAILABLE",
  },
  {
    project: "Blukid Residence 3",
    location: "Sidoarjo",
    block: "B-2",
    shgb: "2761",
    floor: "1 lantai",
    buildingArea: 42,
    landArea: 90,
    price: 817000000,
    status: "AVAILABLE",
  },
  {
    project: "Blukid Residence 3",
    location: "Sidoarjo",
    block: "B-3",
    shgb: "2762",
    floor: "1 lantai",
    buildingArea: 42,
    landArea: 90,
    price: 817000000,
    status: "AVAILABLE",
  },
  {
    project: "Blukid Residence 3",
    location: "Sidoarjo",
    block: "B-4",
    shgb: "2763",
    floor: "1 lantai",
    buildingArea: 42,
    landArea: 90,
    price: 817000000,
    status: "AVAILABLE",
  },
  {
    project: "Blukid Residence 3",
    location: "Sidoarjo",
    block: "B-5",
    shgb: "2764",
    floor: "1 lantai",
    buildingArea: 42,
    landArea: 90,
    price: 817000000,
    status: "AVAILABLE",
  },
  {
    project: "Blukid Residence 3",
    location: "Sidoarjo",
    block: "B-6",
    shgb: "2765",
    floor: "1 lantai",
    buildingArea: 42,
    landArea: 90,
    price: 817000000,
    status: "AVAILABLE",
  },
  {
    project: "Blukid Residence 3",
    location: "Sidoarjo",
    block: "B-7",
    shgb: "2766",
    floor: "1 lantai",
    buildingArea: 42,
    landArea: 90,
    price: 817000000,
    status: "AVAILABLE",
  },
  {
    project: "Blukid Residence 3",
    location: "Sidoarjo",
    block: "B-8",
    shgb: "2767",
    floor: "1 lantai",
    buildingArea: 42,
    landArea: 90,
    price: 817000000,
    status: "AVAILABLE",
  },
  {
    project: "Blukid Residence 3",
    location: "Sidoarjo",
    block: "B-10",
    shgb: "2769",
    floor: "1 lantai",
    buildingArea: 42,
    landArea: 90,
    price: 817000000,
    status: "AVAILABLE",
  },
  {
    project: "Blukid Residence 3",
    location: "Sidoarjo",
    block: "B-11",
    shgb: "2770",
    floor: "1 lantai",
    buildingArea: 42,
    landArea: 90,
    price: 817000000,
    status: "AVAILABLE",
  },
  {
    project: "Blukid Residence 3",
    location: "Sidoarjo",
    block: "B-15",
    shgb: "2773",
    floor: "1 lantai",
    buildingArea: 42,
    landArea: 108,
    price: 984000000,
    status: "AVAILABLE",
  },
  {
    project: "Blukid Residence 3",
    location: "Sidoarjo",
    block: "B-16",
    shgb: "2774",
    floor: "1 lantai",
    buildingArea: 42,
    landArea: 108,
    price: 984000000,
    status: "AVAILABLE",
  },
  {
    project: "Blukid Residence 3",
    location: "Sidoarjo",
    block: "B-18",
    shgb: "2776",
    floor: "1 lantai",
    buildingArea: 42,
    landArea: 129,
    price: 1085000000,
    status: "AVAILABLE",
  },
  {
    project: "Blukid Residence 3",
    location: "Sidoarjo",
    block: "B-20",
    shgb: "2778",
    floor: "1 lantai",
    buildingArea: 42,
    landArea: 90,
    price: 817000000,
    status: "AVAILABLE",
  },
  {
    project: "Blukid Residence 3",
    location: "Sidoarjo",
    block: "B-21",
    shgb: "2779",
    floor: "1 lantai",
    buildingArea: 42,
    landArea: 90,
    price: 817000000,
    status: "AVAILABLE",
  },
  {
    project: "Blukid Residence 3",
    location: "Sidoarjo",
    block: "B-22",
    shgb: "2780",
    floor: "1 lantai",
    buildingArea: 42,
    landArea: 90,
    price: 817000000,
    status: "AVAILABLE",
  },
  {
    project: "Blukid Residence 3",
    location: "Sidoarjo",
    block: "B-23",
    shgb: "2781",
    floor: "1 lantai",
    buildingArea: 42,
    landArea: 90,
    price: 817000000,
    status: "AVAILABLE",
  },
  {
    project: "Blukid Residence 3",
    location: "Sidoarjo",
    block: "B-24",
    shgb: "2782",
    floor: "1 lantai",
    buildingArea: 42,
    landArea: 90,
    price: 817000000,
    status: "AVAILABLE",
  },
  {
    project: "Blukid Residence 3",
    location: "Sidoarjo",
    block: "B-25",
    shgb: "2783",
    floor: "1 lantai",
    buildingArea: 42,
    landArea: 90,
    price: 817000000,
    status: "AVAILABLE",
  },
  {
    project: "Blukid Residence 3",
    location: "Sidoarjo",
    block: "B-26",
    shgb: "2784",
    floor: "1 lantai",
    buildingArea: 42,
    landArea: 90,
    price: 817000000,
    status: "AVAILABLE",
  },
  {
    project: "Blukid Residence 3",
    location: "Sidoarjo",
    block: "C-6",
    shgb: "2795",
    floor: "1 lantai",
    buildingArea: 42,
    landArea: 90,
    price: 817000000,
    status: "AVAILABLE",
  },
  {
    project: "Blukid Residence 3",
    location: "Sidoarjo",
    block: "C-8",
    shgb: "2797",
    floor: "1 lantai",
    buildingArea: 42,
    landArea: 90,
    price: 817000000,
    status: "AVAILABLE",
  },
  {
    project: "Blukid Residence 3",
    location: "Sidoarjo",
    block: "C-10",
    shgb: "2799",
    floor: "1 lantai",
    buildingArea: 42,
    landArea: 90,
    price: 817000000,
    status: "AVAILABLE",
  },
  {
    project: "Blukid Residence 3",
    location: "Sidoarjo",
    block: "C-11",
    shgb: "2800",
    floor: "1 lantai",
    buildingArea: 42,
    landArea: 90,
    price: 817000000,
    status: "AVAILABLE",
  },
  {
    project: "Blukid Residence 3",
    location: "Sidoarjo",
    block: "D-2",
    shgb: "2816",
    floor: "1 lantai",
    buildingArea: 42,
    landArea: 90,
    price: 817000000,
    status: "AVAILABLE",
  },
  {
    project: "Blukid Residence 3",
    location: "Sidoarjo",
    block: "D-9",
    shgb: "2823",
    floor: "1 lantai",
    buildingArea: 42,
    landArea: 90,
    price: 817000000,
    status: "AVAILABLE",
  },
];
